### ISSUE TITLE
Hi! I just cloned your repo and made it work in 2018, can i submit a pull request?

### ISSUE THREAD

**Issue by LukasMeine** [steelejay/LowkeySpeech#2]
.

**Comment by hexicle** [comment]
Just some notes for anyone trying out Lukas's fork.
Lukas's fork works with the latest version of Google Cloud. 
This is a great update.

_If it appears not to be working, please try inspecting the second response in the console more closely_
When you try out the sample project, it will look as if the response is always empty.
This is because in `GoogleVoiceSpeech.cs`, line 133 logs and line 144 prints to the user interface an empty response string.
Therefore it would seem like the API is not providing a response.
However, line 202 logs the response appropriately with the correct response.
This is because unlike the first two lines, line 202 actually runs after the response is received.
To inspect this result, open the console in Unity, and click the log which says

```sh
[01:23:45] Response:{
  "results": [
```
Although it looks like it is just an empty response like the first two outputs would suggest, actually when you expand it it will showthe full response:
```json
Response:{
  "results": [
    {
      "alternatives": [
        {
          "transcript": "hello world",
          "confidence": 0.9872826
        }
      ]
    }
  ]
}
```

**Comment by steelejay** [comment]
Sorry for the delay, I don't check github that much.  Go for it, Lukas. Will it still work with older versions of Unity?

**Comment by LukasMeine** [comment]
Not sure, but I think so.

**Comment by steelejay** [comment]
Go for it. If you say the current version isn't working anyway... it's still progress. ;)

**Comment by LukasMeine** [comment]
@hexicle @steelejay Just submited the pull request. Guess this can be closed now.

**Comment by steelejay** [comment]
Just did the merge, apologies for the delay. Lot going on right now. Thanks.
